/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medaid;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.CallableStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static medaid.changepassword.myConn;
import static medaid.checkdisease.myConn;
import static medaid.loginform.myConn;
import static medaid.newSignup.myConn;

/**
 *
 * @author Sazib
 */
public class enterNewCaseFrame extends javax.swing.JFrame {

    /**
     * Creates new form enterNewCaseFrame
     */
    static String id;
    public enterNewCaseFrame(String id) throws SQLException {
        this.id = id;
        initComponents();
        myConn = Conn.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter New Case");
        setBackground(new java.awt.Color(5, 102, 141));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(255, 255, 204));
        jTextField1.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 610, 30));

        jTextField2.setBackground(new java.awt.Color(255, 255, 204));
        jTextField2.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 610, 40));

        jTextField3.setBackground(new java.awt.Color(255, 255, 204));
        jTextField3.setForeground(new java.awt.Color(0, 153, 153));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 270, 40));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upload.png"))); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 260, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enter new case psd.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(!(jTextField1.getText().equals("") || jTextField2.getText().equals("") || jTextField3.getText().equals(""))){
            
            try {
                stmt = (PreparedStatement) myConn.prepareStatement("select * from patient_info where patient_id=?");
                stmt.setInt(1, Integer.parseInt(jTextField3.getText()));
                myRs = stmt.executeQuery();
                
                if (!myRs.isBeforeFirst() ) {    
                    JOptionPane.showMessageDialog(null, "Unknown patient ID.");
                }else {
                    stmt = (PreparedStatement) myConn.prepareStatement("select * from disease_info where disease_name=?");
                    stmt.setString(1, jTextField1.getText());
                    myRs = stmt.executeQuery();

                    if (!myRs.isBeforeFirst() ) {    
                        JOptionPane.showMessageDialog(null, "Unknown disease name.");
                    }else {
                        uploadCase();
                        JOptionPane.showMessageDialog(null, "Update Successful.");
                    }
                }
              
            } catch (SQLException ex) {
                Logger.getLogger(enterNewCaseFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please enter all information!");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    public void uploadCase(){
        try {
                PreparedStatement myStmt1 = (PreparedStatement) myConn.prepareStatement("SELECT disease_id FROM disease_info where disease_name=?");
                myStmt1.setString(1,jTextField1.getText());
                ResultSet myRs1 = myStmt1.executeQuery();
                myRs1.next();
                CallableStatement myStmt;
                myStmt = myConn.prepareCall("{call insert_case(?, ?, ?, ?)}");
                myStmt.setInt(1, myRs1.getInt("disease_id"));

                DateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd");
                Date date = new Date();

                myStmt.setString(2, dateFormat.format(date));
                myStmt.setString(3, jTextField2.getText());
                myStmt.registerOutParameter(4, Types.INTEGER);
                myStmt.execute();
                ResultSet myRs2 = myStmt.getResultSet();
                myRs2.next();

                CallableStatement myStmt2;
                myStmt2 = myConn.prepareCall("{call doctor_patient_case(?, ?, ?)}");
                myStmt2.setInt(1, Integer.parseInt(id));
                myStmt2.setInt(2, Integer.parseInt(jTextField3.getText()));
                myStmt2.setInt(3, myRs2.getInt("case_id"));
                myStmt2.execute();// TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(enterNewCaseFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enterNewCaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enterNewCaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enterNewCaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enterNewCaseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new enterNewCaseFrame(id).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(enterNewCaseFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    PreparedStatement stmt;
    ResultSet myRs;
    static Connection myConn;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
