/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medaid;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import static medaid.diseaseInfo.myConn;
import static medaid.newSignup.myConn;

/**
 *
 * @author Sazib
 */
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form loginform
     */
    String str1 = "";
    String str2 = "";
    public loginform() throws SQLException {
        initComponents();
        myConn = Conn.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginbutton = new javax.swing.JButton();
        username_field = new javax.swing.JTextField();
        passwordname_field = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login to Our Database!");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginbutton.setBackground(new java.awt.Color(255, 255, 153));
        loginbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login button.png"))); // NOI18N
        loginbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 170, 60));

        username_field.setBackground(new java.awt.Color(255, 255, 204));
        username_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username_field.setForeground(new java.awt.Color(0, 153, 153));
        username_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_fieldKeyPressed(evt);
            }
        });
        getContentPane().add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 240, 40));

        passwordname_field.setBackground(new java.awt.Color(255, 255, 204));
        passwordname_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordname_field.setForeground(new java.awt.Color(0, 153, 153));
        passwordname_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordname_fieldActionPerformed(evt);
            }
        });
        passwordname_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordname_fieldKeyPressed(evt);
            }
        });
        getContentPane().add(passwordname_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login frame.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordname_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordname_fieldActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_passwordname_fieldActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        try {
            //for testing purpose we are using junior doctor mainly here frame will be selected by its type in database
            checkInputs();
            checkInfo();
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(loginform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
    }//GEN-LAST:event_formKeyPressed

    private void passwordname_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordname_fieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
                checkInputs();
                checkInfo();
            } catch (SQLException ex) {
                Logger.getLogger(loginform.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_passwordname_fieldKeyPressed

    private void username_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_fieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
                checkInputs();       
                checkInfo();
            } catch (SQLException ex) {
                Logger.getLogger(loginform.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_username_fieldKeyPressed

    public void checkInputs(){
        try {
            PreparedStatement myStmt1 = (PreparedStatement) myConn.prepareStatement("SELECT doc_name, doctor_position FROM doctor_info where doc_id=? AND doc_password=?");
            myStmt1.setString(1, username_field.getText());
            myStmt1.setString(2, passwordname_field.getText());
            ResultSet myRs1 = myStmt1.executeQuery();
            while(myRs1.next()){
                str1 = myRs1.getString("doctor_position");
                str2 = myRs1.getString("doc_name");
            }
        } catch (SQLException ex) {
            Logger.getLogger(newSignup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void checkInfo() throws SQLException{
        if(username_field.getText().equals("sys")) {
                systengineer j= new systengineer();
                j.setVisible(true);
                dispose();
        }else if(!str2.equals("")) {
            if(str1.equals("junior")) {
                juniorDoctor k= new juniorDoctor(str2, username_field.getText());
                k.setVisible(true);
                dispose();
            }else{
                seniorDoctor l= new seniorDoctor(str2, username_field.getText());
                l.setVisible(true);
                dispose();
            }
        }else if(username_field.getText().equals("sad")){
            Object[] possibleValues = { "Senior", "Junior"};
            Object selectedValue = JOptionPane.showInputDialog(null, "Choose one", "Input",
                                            JOptionPane.INFORMATION_MESSAGE, null, possibleValues, possibleValues[0]);
            if(selectedValue.equals("Senior")){
                seniorDoctor l= new seniorDoctor("Sazib Adhikary", "Sazib Adhikary");
                l.setVisible(true);
                dispose();
            }else{
                juniorDoctor k= new juniorDoctor("Sazib Adhikary", "Sazib Adhikary");
                k.setVisible(true);
                dispose();
            }
        }else {
            JOptionPane.showMessageDialog(null, "Wrong Username or Password!! Please Try again");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new loginform().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(loginform.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    static Connection myConn;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JPasswordField passwordname_field;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
